# Generated by Django 5.2.3 on 2025-06-30 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_alter_producto_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='precio_individual_bs',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='producto',
            name='precio_individual_dolar',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
