# Generated by Django 5.2.3 on 2025-07-02 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_alter_producto_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='porcentaje_ganancia',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
