# Generated by Django 5.2.3 on 2025-06-29 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TasaBCV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(unique=True)),
                ('valor', models.DecimalField(decimal_places=4, max_digits=12)),
                ('activa', models.BooleanField(default=False)),
            ],
        ),
    ]
