# Generated by Django 5.2.3 on 2025-07-02 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasabcv',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
