# Generated by Django 5.2.3 on 2025-07-03 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0003_rename_observaciones_venta_comentario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventaitem',
            name='cantidad',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
        ),
    ]
