# Generated by Django 5.2.3 on 2025-07-03 16:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0004_alter_ventaitem_cantidad'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ventaitem',
            options={},
        ),
        migrations.RenameField(
            model_name='venta',
            old_name='comentario',
            new_name='observaciones',
        ),
        migrations.AlterField(
            model_name='venta',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas', to='ventas.cliente'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('COMPLETADA', 'Completada'), ('ANULADA', 'Anulada'), ('DEVOLUCION', 'Devolución')], default='COMPLETADA', max_length=50),
        ),
        migrations.AlterField(
            model_name='venta',
            name='metodo_pago',
            field=models.CharField(choices=[('EFECTIVO_USD', 'Efectivo USD'), ('EFECTIVO_BS', 'Efectivo Bs'), ('PUNTO_DEBITO', 'Punto de Débito'), ('PUNTO_CREDITO', 'Punto de Crédito'), ('TRANSFERENCIA', 'Transferencia'), ('PAGO_MOVIL', 'Pago Móvil'), ('ZELLE', 'Zelle'), ('BINANCE_PAY', 'Binance Pay'), ('MIXTO', 'Mixto'), ('OTRO', 'Otro')], default='EFECTIVO_USD', max_length=50),
        ),
        migrations.AlterField(
            model_name='venta',
            name='tasa_bcv_venta',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='venta',
            name='total_bs',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='venta',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas_realizadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ventaitem',
            name='cantidad',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='ventaitem',
            name='precio_unitario_dolar',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='ventaitem',
            name='subtotal_bs',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='ventaitem',
            name='subtotal_dolar',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
