# Generated by Django 5.2.3 on 2025-07-07 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0005_alter_ventaitem_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='total_deuda',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='venta',
            name='estado',
            field=models.CharField(choices=[('ADEUDADO', 'Adeudado'), ('COMPLETADA', 'Completada'), ('ANULADA', 'Anulada'), ('DEVOLUCION', 'Devolución')], default='COMPLETADA', max_length=50),
        ),
    ]
