# Generated by Django 5.2.3 on 2025-07-09 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0007_remove_cliente_total_deuda_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='estado',
            field=models.CharField(choices=[('ADEUDADO', 'Adeudado'), ('COMPLETADA', 'Completada'), ('ANULADA', 'Anulada'), ('DEVOLUCION', 'Devolución')], default='COMPLETADA', max_length=20),
        ),
        migrations.AlterField(
            model_name='venta',
            name='metodo_pago',
            field=models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TARJETA_DEBITO', 'Tarjeta de Débito'), ('TARJETA_CREDITO', 'Tarjeta de Crédito'), ('TRANSFERENCIA', 'Transferencia'), ('PAGO_MOVIL', 'Pago Móvil'), ('MIXTO', 'Mixto'), ('ZELLE', 'Zelle'), ('CRIPTO', 'Cripto'), ('OTRO', 'Otro')], default='MIXTO', max_length=20),
        ),
    ]
