# Generated by Django 5.2.3 on 2025-07-09 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0008_alter_venta_estado_alter_venta_metodo_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='metodo_pago',
            field=models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TARJETA_DEBITO', 'Tarjeta de Débito'), ('TARJETA_CREDITO', 'Tarjeta de Crédito'), ('TRANSFERENCIA', 'Transferencia'), ('PAGO_MOVIL', 'Pago Móvil'), ('MIXTO', 'Mixto'), ('ZELLE', 'Zelle'), ('CRIPTO', 'Cripto'), ('OTRO', 'Otro')], default='EFECTIVO', max_length=20),
        ),
    ]
